# Generated by Django 3.2 on 2021-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210419_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
