# Generated by Django 3.2 on 2021-04-20 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210420_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='pantry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='core.pantry'),
        ),
    ]
