# Generated by Django 3.2 on 2021-04-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
