# Generated by Django 3.2 on 2021-04-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_shoppinglist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients_info', through='core.RecipeIngredient', to='core.Ingredient'),
        ),
    ]
