# Generated by Django 3.2 on 2021-04-27 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210425_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pantry',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='pantry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pantry_ingredients', to='core.pantry'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='shoppinglist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglist_ingredients', to='core.shoppinglist'),
        ),
        migrations.CreateModel(
            name='SelectedRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='selectedrecipes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_recipes', to='core.selectedrecipes'),
        ),
    ]
