# Generated by Django 3.2 on 2021-04-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210427_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
