# Generated by Django 3.2 on 2021-05-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210430_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredient', through='core.RecipeIngredient', to='core.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(max_length=150),
        ),
    ]
